### PR TITLE
Knuth bendix performance improvements

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR contains a number of changes aimed at improving the performance of the Knuth-Bendix implementation in libsemigroups.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@Joseph-Edwards any ideas why the Cygwin CI is failing? Is it a too big executable issue do you think? If you have a minute (at some point, not necessarily right away, it's Sunday after all) can you please try to reproduce locally? 

If it is a too big executable issue, then maybe we can switch to compiling+running each test executable separately?

**Comment by james-d-mitchell** [comment]
@codecov-ai-reviewer test

**Comment by james-d-mitchell** [comment]
Thanks @Joseph-Edwards. I wonder if this is an actual issue or just some Cygwin weirdness. Can you try bisecting to see which commit caused the issue? Thanks!

**Comment by Joseph-Edwards** [comment]
Bisect gives me:
```git
bd2744d1e1404804f49baaa6020fee342cb0a749 is the first bad commit
commit bd2744d1e1404804f49baaa6020fee342cb0a749 (HEAD)
Author: James Mitchell <jdm3@st-andrews.ac.uk>
Date:   Wed Jul 9 16:09:12 2025 +0100

    string: remove unused fn

 include/libsemigroups/detail/string.hpp | 12 ------------
 1 file changed, 12 deletions(-)
```

However, the reason the above commit is "bad" is because it doesn't compile:
```
  CXX      src/detail/libsemigroups_la-rewriters.lo
src/detail/rewriters.cpp: In member function 'virtual void libsemigroups::detail::RewriteFromLeft::rewrite(libsemigroups::detail::internal_string_type&) const':
src/detail/rewriters.cpp:372:21: error: 'string_replace' is not a member of 'libsemigroups::detail'
  372 |             detail::string_replace(
      |                     ^~~~~~~~~~~~~~
src/detail/rewriters.cpp: In member function 'virtual void libsemigroups::detail::RewriteTrie::rewrite(libsemigroups::detail::internal_string_type&) const':
src/detail/rewriters.cpp:599:19: error: 'string_replace' is not a member of 'libsemigroups::detail'
  599 |           detail::string_replace(
      |                   ^~~~~~~~~~~~~~
make: *** [Makefile:3777: src/detail/libsemigroups_la-rewriters.lo] Error 1
```
which is unrelated. I checked manually and there are no later tests that compile but cause the `Abort`

**Comment by james-d-mitchell** [comment]
So it's that one or the one after that introduces whatever is causing it to fail?

**Comment by Joseph-Edwards** [comment]
I've done a bit more digging. A MWE of a file that causes the abort problem is:
```cpp
#define CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS

#include "Catch2-3.8.0/catch_amalgamated.hpp"  // for TEST_CASE
#include "test-main.hpp"                       // for LIBSEMIGROUPS_TEST_CASE

#include "libsemigroups/todd-coxeter.hpp"
#include "libsemigroups/cong.hpp"                   // for Congruence
#include "libsemigroups/presentation.hpp"			// for presentation, Presentation

namespace libsemigroups {

  using literals::operator""_w;
  
  constexpr congruence_kind onesided = congruence_kind::onesided;

  LIBSEMIGROUPS_TEST_CASE("Congruence", "000", "basic", "[quick][cong]") {
    Presentation<word_type> p;
    p.alphabet(2);
    presentation::add_rule(p, 000_w, 0_w);
    Congruence cong(onesided, p);
  }
}  // namespace libsemigroups
```

Using gdb, I can get the ever-so-slightly more informative message 
```
Thread 1 "test_cong" received signal SIGABRT, Aborted.
0x00007ffe4eb917a4 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
```

which is thrown when trying constructing the shared pointer in `cong-class.tpp:67`:
``` cpp
  template <typename Word>
  Congruence<Word>& Congruence<Word>::init(congruence_kind           type,
                                           Presentation<Word> const& p) {
    init();
    detail::CongruenceCommon::init(type);
    _race.max_threads(POSITIVE_INFINITY);
    if (type == congruence_kind::twosided) {
      add_runner(std::make_shared<Kambites<Word>>(type, p));
    }
    add_runner(std::make_shared<KnuthBendix<Word>>(type, p)); // <- This line is where the error is thrown.

    add_runner(std::make_shared<ToddCoxeter<Word>>(type, p));
    auto tc = std::make_shared<ToddCoxeter<Word>>(type, p);
    tc->strategy(ToddCoxeter<Word>::options::strategy::felsch);
    add_runner(std::move(tc));
    return *this;
  }
```
I'll do some more digging to try and get anything else.

**Comment by Joseph-Edwards** [comment]
I did another bisect, but this time I also fixed the `string_replace` error as I bisected that was preventing the compilation (which was hiding whether or not `test_cong` would abort). The commit that introduced the cygwin problems is 7562ff38573b4013a28c4cba5d0a2b582b32c6eb. @james-d-mitchell, let me know if there is anything else you'd like me to try.

**Comment by james-d-mitchell** [comment]
> I did another bisect, but this time I also fixed the `string_replace` error as I bisected that was preventing the compilation (which was hiding whether or not `test_cong` would abort). The commit that introduced the cygwin problems is 7562ff38573b4013a28c4cba5d0a2b582b32c6eb. @james-d-mitchell, let me know if there is anything else you'd like me to try.  

Thanks @Joseph-Edwards, this is super helpful. Maybe we can have a call later today to try to pin down what's going wrong?

**Comment by james-d-mitchell** [comment]
@Joseph-Edwards looks like the "no-cygwin" tests are still being run in the Cygwin job, can you please amend this?

**Comment by Joseph-Edwards** [comment]
Once the CI passes, I'll review the code and then merge if you're happy with everything @james-d-mitchell?

File: include/libsemigroups/detail/knuth-bendix-impl.tpp [hunk 1]
```diff
@@ -17,66 +17,64 @@
...
-        }
-      }
-    }
+
+    void prefixes_string(std::unordered_map<u8string,
+                                            size_t,
+                                            Hash<u8string>,
+                                            std::equal_to<u8string>>& st,
+                         u8string const&                              x,
+                         size_t&                                      n);
```
[the remark this answers is not in the document]
Comment (james-d-mitchell) [reply include/libsemigroups/detail/knuth-bendix-impl.tpp:35]: Didn't want to expose this, so happy enough to do either!

File: include/libsemigroups/detail/rewriters.hpp [hunk 2]
```diff
@@ -402,296 +237,280 @@ namespace libsemigroups {
...
-        return _alphabet.cbegin();
-      }
+      ////////////////////////////////////////////////////////////////////////
+      // Public mem fns
+      ////////////////////////////////////////////////////////////////////////
 
-      alphabet_citerator alphabet_cend() const {
-        return _alphabet.cend();
+      RewriteBase& increase_alphabet_size_by(size_t) {
+        return *this;
```
[the remark this answers is not in the document]
Comment (james-d-mitchell) [reply include/libsemigroups/detail/rewriters.hpp:313]: Good question I have no idea will check!
